{% set version = "0.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bundle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bundle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bundle/bundle_{{ version }}.tar.gz
  sha256: 5fea189ce80c8a0b4bc9424ad9835cfa4774202f37797dc8a2cb990b270974ac

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
    - r-purrr
    - r-rlang
    - r-withr
  run:
    - r-base
    - r-glue
    - r-purrr
    - r-rlang
    - r-withr

test:
  requires:
    - r-testthat >=3.0.0
    - r-butcher
    - r-caret
    - r-kernlab
    - r-parsnip
    - r-recipes
    - r-stacks
    - r-workflows
    - r-xgboost
  source_files:
    - tests/testthat/
    - tests/testthat.R
  commands:
    - $R -e "library('bundle')"                                                       # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('bundle')\""                                              # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://rstudio.github.io/bundle/
  dev_url: https://github.com/rstudio/bundle
  license: MIT
  summary: Typically, models in 'R' exist in memory and can be saved via regular 'R' serialization. However, some models store information in locations that cannot be saved using 'R' serialization alone. The goal of 'bundle' is to provide a common interface to capture this information, situate it within a portable object,
    and restore it for use in new settings.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
